version: '3'
services:
  ubuntu-dind:
    image: anujatel/ubuntu-dind:v2
    build: ./Docker/Dockerfile-Dind-ubuntu-mlops
    container_name: ubuntu-dind
    volumes:
      - ${PWD}:/app
      - /lib/modules:/lib/modules:ro
    working_dir: /app
    command: [ "bash" ]
    privileged: true # to run docker commands inside the container
    stdin_open: true # interactive
    tty: true # tty
    network_mode: host
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    tmpfs:
      - /tmp
      - /run
      - /run/lock
