sonar.organization=anujatelDevSecOps
sonar.projectKey=wonderlust

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=src