---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
  namespace: admin
  labels:
    name:  admin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-ui
  template:
    metadata:
      labels:
        app: admin-ui
        module: admin
    spec:
      volumes:
        - name: admin-ui-vl
          configMap:
            name: admin-ui-cm
      nodeSelector:
        instance: admin # Need to set this
      containers:
      - name: admin-ui
        image: # NEED to be added
        ports: 
        - containerPort: 3000
          name: http
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits: 
            memory: "2Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        volumeMounts:
          - name: admin-ui-vl
            mountPath: /app/.env
            subPath: .env

---
apiVersion: v1
kind: Service
metadata:
  name: admin-ui-svc
  namespace: admin
spec:
  type: ClusterIP
  selector:
    app: admin-ui
    module: admin
  ports:
  - port: 3000
    targetPort: 3000