apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-ui-cm
  namespace: admin
  labels:
    app: admin-ui
data:
  .env: |
      REACT_APP_API_URL= http://admin-api-svc:3000

# This needs tobe changed to the external IP of the admin-api service 