apiVersion: v1
kind: ConfigMap
metadata:
  name: user-ui-cm
  namespace: user
  labels:
    app: user-ui
data:
  .env: |
      REACT_APP_API_URL= http://user-api-svc:3000

# This needs tobe changed to the external IP of the user-api service 