---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ui
  namespace: user
  labels:
    name: user-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-ui
  template:
    metadata:
      labels:
        app: user-ui
        module: user
    spec:
      volumes:
        - name: user-ui-vl
          configMap:
            name: user-ui-cm
      nodeSelector:
        instance: user # Need to set this
      containers:
      - name: user-ui
        image: anujatel/user-ui:v3
        ports: 
        - containerPort: 3000
          name: http
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits: 
            memory: "2Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        volumeMounts:
          - name: user-ui-vl
            mountPath: /app/.env
            subPath: .env

