apiVersion: v1
kind: Secret
metadata:
  name: user-api-secrets
  namespace: user
type: Opaque
data:
  connectionstring: bW9uZ29kYjovL21vbmdvYWRtaW46c2VjcmV0QG1vbmdvLWRiLXN2Yy5kYXRhYmFzZS5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5

# mongodb://mongoadmin:secret@mongo-db-svc.database.svc.cluster.local:27017/?retryWrites=true&w=majority 