---
apiVersion: v1
kind: Service
metadata:
  name: admin-api-svc
  namespace: admin
spec:
  selector:
    app: admin-api
    module: admin
  ports:
    - protocol: TCP
      port: 1004
      targetPort: 1004
  type: ClusterIP