FROM cruizba/ubuntu-dind:latest

LABEL REPOSITORY="https://github.com/atelanuj/DevSecOps_end_to_end/tree/Voting-Application/Docker"
LABEL MAINTAINER="atelanuj"

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    python3 \
    python3-pip \
    python3-venv \
    vim \
    tree \
    git && \
    rm -rf /var/lib/apt/lists/*

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt .

RUN pip install -r requirements.txt

CMD ["bash"]
