---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  namespace: user
  labels:
    name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
        module: user
    spec:
      nodeSelector:
        instance: user # Need to set this
      containers:
      - name: user-api
        image: # NEED to be added
        ports: 
        - containerPort: 1004
          name: http
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: mongo-db-secrets
                key: connectionstring
          - name: PORT
            value: "1004"
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits: 
            memory: "2Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 1004
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 1004
          initialDelaySeconds: 30
          timeoutSeconds: 10

