---
name: CallBooking application CI admin-ui
    
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - admin-ui/
    
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        
        - name: Docker login
          run: |
            docker login -u "${{ secrets.DOCKERHUB_USER }}" -p "${{ secrets.DOCKERHUB_PASS }}"

        - name: Build and Push Admin UI image
          run: |
            echo "Building and pushing Admin UI image"
            docker build -t admin-ui ./admin-ui
            docker tag admin-ui ${{ secrets.DOCKERHUB_USER }}/admin-ui:v${{github.run_number}}
            docker push ${{ secrets.DOCKERHUB_USER }}/admin-ui:v${{github.run_number}}

    Deploy:
        runs-on: ubuntu-latest
        needs: build-and-push
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Updating the tag in Manifests for Latest Image.
          run: |
            sed -i 's|image:.*|image: '"${{ secrets.DOCKERHUB_USER }}"'/admin-ui:v'"${{github.run_number}}"'|g' k8s/admin-ui/deployment.yml
            echo "Updated the tag in Manifests for ADMIN UI with Latest Image."