---
name: CallBooking application CI admin-api
    
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - admin-api/**
        
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: Docker login
              run: |
                docker login -u "${{ vars.DOCKER_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASS }}"
    
            - name: Build and Push Admin UI image
              run: |
                echo "Building and pushing Admin UI image"
                docker build -t admin-api ./admin-api
                docker tag admin-api ${{ vars.DOCKER_USERNAME }}/admin-api:v${{github.run_number}}
                docker push ${{ vars.DOCKER_USERNAME }}/admin-api:v${{github.run_number}}
    
    Deploy:
        runs-on: ubuntu-latest
        needs: build-and-push
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
    
            - name: Updating the tag in Manifests for Latest Image.
              run: |
                sed -i 's|image:.*|image: '"${{ vars.DOCKER_USERNAME }}"'/admin-api:v'"${{github.run_number}}"'|g' k8s/admin-api/deployment.yml
                echo "Updated the tag in Manifests for ADMIN UI with Latest Image."