# ---
# name: CallBooking application CI

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main
#     # paths:
#     #   - admin-ui/
#     #   - admin-api/
#     #   - user-ui/
#     #   - user-api/

# jobs:
#   detect-changes:
#     runs-on: ubuntu-latest
#     outputs:
#       admin-ui-changed: ${{ steps.check.outputs.admin-ui-changed }}
#       admin-api-changed: ${{ steps.check.outputs.admin-api-changed }}
#       user-ui-changed: ${{ steps.check.outputs.user-ui-changed }}
#       user-api-changed: ${{ steps.check.outputs.user-api-changed }}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: test
#         run: | 
#           git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^.github/workflows/ci.yml"
#           git diff --name-only "${{ github.event.before }}" "${{ github.sha }}" | grep "^admin-ui/" >/dev/null

#       - name: Check for changes
#         id: check
#         run: |
#           # Check if files in the admin-ui directory have changed
#           if git diff ${{ github.event.before }} ${{ github.sha }} --name-only | grep "admin-ui/"; then
#             echo "admin-ui-changed=true" >> $GITHUB_ENV
#             echo "admin-ui-changed=true" >> $GITHUB_OUTPUT
#           else
#             echo "admin-ui-changed=false" >> $GITHUB_ENV
#             echo "admin-ui-changed=false" >> $GITHUB_OUTPUT
#           fi

#           # Check if files in the admin-api directory have changed
#           if git diff ${{ github.event.before }} ${{ github.sha }} --name-only | grep "admin-api/"; then
#             echo "admin-api-changed=true" >> $GITHUB_ENV
#             echo "admin-api-changed=true" >> $GITHUB_OUTPUT
#           else
#             echo "admin-api-changed=false" >> $GITHUB_ENV
#             echo "admin-api-changed=false" >> $GITHUB_OUTPUT
#           fi

#           # Check if files in the user-ui directory have changed
#           if git diff ${{ github.event.before }} ${{ github.sha }} --name-only | grep "user-ui/"; then
#             echo "user-ui-changed=true" >> $GITHUB_ENV
#             echo "user-ui-changed=true" >> $GITHUB_OUTPUT
#           else
#             echo "user-ui-changed=false" >> $GITHUB_ENV
#             echo "user-ui-changed=false" >> $GITHUB_OUTPUT
#           fi

#           # Check if files in the user-api directory have changed
#           if git diff ${{ github.event.before }} ${{ github.sha }} --name-only | grep "user-api/"; then
#             echo "user-api-changed=true" >> $GITHUB_ENV
#             echo "user-api-changed=true" >> $GITHUB_OUTPUT
#           else
#             echo "user-api-changed=false" >> $GITHUB_ENV
#             echo "user-api-changed=false" >> $GITHUB_OUTPUT

#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Docker login
#         run: |
#           docker login -u "${{ secrets.DOCKERHUB_USER }}" -p "${{ secrets.DOCKERHUB_PASS }}"

#       - name: Build and Push Admin UI image
#         if: env.admin-ui-changed == 'true'
#         run: |
#           echo "Building and pushing Admin UI image"
#           docker build -t admin-ui ./admin-ui
#           docker tag admin-ui ${{ secrets.DOCKERHUB_USER }}/admin-ui:v${{github.run_number}}
#           docker push ${{ secrets.DOCKERHUB_USER }}/admin-ui:v${{github.run_number}}

#       - name: Build and Push Admin API image
#         if: env.admin-api-changed == 'true'
#         run: |
#           echo "Building and pushing Admin API image"
#           docker build -t admin-api ./admin-api
#           docker tag admin-api ${{ secrets.DOCKERHUB_USER }}/admin-api:v${{github.run_number}}
#           docker push ${{ secrets.DOCKERHUB_USER }}/admin-api:v${{github.run_number}}

#       - name: Build and Push User UI image
#         if: env.user-ui-changed == 'true'
#         run: |
#           echo "Building and pushing User UI image"
#           docker build -t user-ui ./user-ui
#           docker tag user-ui ${{ secrets.DOCKERHUB_USER }}/user-ui:v${{github.run_number}}
#           docker push ${{ secrets.DOCKERHUB_USER }}/user-ui:v${{github.run_number}}
  
#       - name: Build and Push User API image
#         if: env.user-api-changed == 'true'
#         run: |
#           echo "Building and pushing User API image"
#           docker build -t user-api ./user-api
#           docker tag user-api ${{ secrets.DOCKERHUB_USER }}/user-api:v${{github.run_number}}
#           docker push ${{ secrets.DOCKERHUB_USER }}/user-api:v${{github.run_number}}

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build-and-push
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Updating the tag in Manifests for Latest Image.
#         run: |
#           sed -i 's|image:.*|image: '"${{ secrets.DOCKERHUB_USER }}"'/admin-ui:v'"${{github.run_number}}"'|g' k8s/admin-ui/deployment.yml
#           sed -i 's|image:.*|image: '"${{ secrets.DOCKERHUB_USER }}"'/admin-api:v'"${{github.run_number}}"'|g' k8s/admin-api/deployment.yml
#           sed -i 's|image:.*|image: '"${{ secrets.DOCKERHUB_USER }}"'/user-ui:v'"${{github.run_number}}"'|g' k8s/user-ui/deployment.yml
#           sed -i 's|image:.*|image: '"${{ secrets.DOCKERHUB_USER }}"'/user-api:v'"${{github.run_number}}"'|g' k8s/user-api/deployment.yml
#           echo "Updated the tag in Manifests for Latest Image."