name: Wonder-Lust Travel App DevSecOps CI/CD Pipeline

on: 
    workflow_dispatch:
    push:
        branches:
            - Wonder_lust_jenkins_end_to_end
        paths:
            - frontend/**
            - backend/**
            - kubernetes/**

env:
    # Frontend_tag: ${{ github.run_number }}
    # Backend_tag: ${{ github.run_number }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    DATREE_SCAN_PATH: "./kubernetes"
    OWASP_REPORT_PATH: "./reports/dependency-check-report.html"
    FRONTEND_IMAGE: ${{ vars.DOCKER_USERNAME }}/wonderlust-frontend:v${{ github.run_number }}
    BACKEND_IMAGE: ${{ vars.DOCKER_USERNAME }}/wonderlust-backend:v${{ github.run_number }}
    FRONTEND_DEPLOYMENT_MANIFEST: "./kubernetes/frontend.yaml"
    BACKEND_DEPLOYMENT_MANIFEST: "./kubernetes/backend.yaml"
    # DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} # fetch from https://hub.datree.io/dashboard/account-token#1-get-your-account-token-from-the-dashboard

jobs:
    Security-Scan:
        name: Security Scan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
        
            - name: Install JAVA latest
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '21'
                java-package: 'jdk'
                check-latest: true

            # - name: SonarQube Scan
            #   id: sonarqube-scan
            #   uses: SonarSource/sonarqube-scan-action@v4.2.1
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #     SONAR_TOKEN: ${{env.SONAR_TOKEN}}
            #     SONAR_HOST_URL: ${{env.SONAR_HOST_URL}}

            # - name: SonarQube Server Quality Gate check
            #   id: sonarqube-quality-gate-check
            #   uses: sonarsource/sonarqube-quality-gate-action@master
            #   with:
            #     pollingTimeoutSec: 600
            #   timeout-minutes: 8
            #   env:
            #     SONAR_TOKEN: ${{env.SONAR_TOKEN}}
            #     SONAR_HOST_URL: ${{env.SONAR_HOST_URL}} #OPTIONAL  

            # - name: "Example show SonarQube Server Quality Gate Status value"
            #   run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
              
            - name: Run Datree k8s Manifests Policy Check
              continue-on-error: true
              uses: datreeio/action-datree@main
              with:
               path: ${{ env.DATREE_SCAN_PATH }}
               cliArguments: '--only-k8s-files'
    
            - name: OWASP Dependency check
              uses: dependency-check/Dependency-Check_Action@main
              continue-on-error: true
              id: Depcheck
              env:
                JAVA_HOME: /opt/jdk
              with:
                project: 'Wonder-Lust Travel App'
                path: '.'
                format: 'HTML'
                out: 'reports'
                args: >
                  --failOnCVSS 7
                  --enableRetired
        
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              continue-on-error: true
              with:
                name: OWASP-dependency-report
                path: ${{ env.OWASP_REPORT_PATH }}
        
            - name: Run Trivy vulnerability scanner on filesystem
              uses: aquasecurity/trivy-action@0.28.0
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'sarif'
                output: 'trivy-results.sarif'
                severity: 'CRITICAL'
            
            
    Build-And-test:
        name: Build And Test
        needs: Security-Scan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Frontend Unit Testing
              continue-on-error: true
              run: |
                cd ./frontend
                echo 'Installing dependencies'
                npm install
                echo 'Running tests'
                npm run test
              
            - name: Backend Unit Testing
              continue-on-error: true
              run: |
                cd ./backend
                echo 'Installing dependencies'
                npm install
                echo 'Running tests'
                npm run test

            - name: Docker login
              run: |
                docker login -u "${{ vars.DOCKER_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASS }}"

            - name: Frontend Docker Build
              run: |
                cd ./frontend
                docker build -t ${{env.FRONTEND_IMAGE}} .

            - name: Backend Docker Build
              run: |
                cd ./backend
                docker build -t ${{env.BACKEND_IMAGE}} .

            - name: Run Trivy vulnerability scanner on Frontend Docker image
              uses: aquasecurity/trivy-action@0.28.0
              continue-on-error: true
              with:
                image-ref: '${{ env.FRONTEND_IMAGE }}'
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL,HIGH'

            - name: Run Trivy vulnerability scanner on Backend Docker image
              uses: aquasecurity/trivy-action@0.28.0
              continue-on-error: true
              with:
                image-ref: '${{ env.BACKEND_IMAGE }}'
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL,HIGH'

            - name: Push Frontend Docker Image
              run: |
                docker push ${{env.FRONTEND_IMAGE}}

            - name: Push Backend Docker Image
              run: |
                docker push ${{env.BACKEND_IMAGE}}

                
    Deploy:
        name: Deploy
        needs: Build-And-test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Updating the tag in frontend Deployment Manifests for Latest Image
              run: |
                sed -i 's|image:.*|image: ${{ env.FRONTEND_IMAGE }}|g' ${{ env.FRONTEND_DEPLOYMENT_MANIFEST }}
                sed -i 's|image:.*|image: ${{ env.BACKEND_IMAGE }}|g' ${{ env.BACKEND_DEPLOYMENT_MANIFEST }}
                git config --local user.email "github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
                git pull
                git commit -a -m "Updated the Image to ${{ env.FRONTEND_IMAGE }} and ${{ env.BACKEND_IMAGE }}"
                echo "Updated the tag in frontend/backend Deployments Manifests for Latest Image."
    
            - name: Deploy to Kubernetes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GIT_TOKEN }}
                branch: ${{ github.ref }}