name: Terraform Deployment
on: [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform

    steps:
      - uses: actions/checkout@v4

      - name: Fetch Keys from Vault
        uses: hashicorp/vault-action@v3
        with:
        #   url: http://[IP_ADDRESS]:8200
          url: http://13.234.238.41:8200
          role: gh-actions-role
          method: jwt
          secrets: | # pragma: allowlist secret
            aws/creds/terraform-role accessKey | AWS_ACCESS_KEY_ID ;
            aws/creds/terraform-role secretKey | AWS_SECRET_ACCESS_KEY

      - name: Print the Creds
        run: |
          echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}"
          echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}"

    #   - uses: hashicorp/setup-terraform@v3
    #   - run: terraform init
    #   - run: terraform plan
    #   - run: terraform apply -auto-approve