name: Terraform Deployment
on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Terraform_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform/EC2 + VPC + EKS

    steps:
      - uses: actions/checkout@v4

      - name: Fetch Keys from Vault
        uses: hashicorp/vault-action@v3
        with:
        #   url: http://[IP_ADDRESS]:8200
          url: http://ec2-13-235-0-46.ap-south-1.compute.amazonaws.com:8200
          role: gh-actions-role
          method: jwt
          secrets: | # pragma: allowlist secret
            aws/creds/terraform-role access_key | AWS_ACCESS_KEY_ID ;
            aws/creds/terraform-role secret_key | AWS_SECRET_ACCESS_KEY

      - name: Print the Creds
        run: |
          echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}"
          echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}"

      - uses: hashicorp/setup-terraform@v3
      - run: pwd
      - run: ls -l
      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve